<!--@package     Andersongustavo_Sociallinks-->
<!--@author      Anderson Gustavo Rodrigues Alves - anderson.quata@hotmail.com-->

<?php if($this->isEnabled()): ?>
<div class="feature-products-wrapper">
    <div class="feature-products-header">
        <?= ($header = $this->getHeader()) ? '<h2>'.$header.'</h2>' : ''; ?>
    </div>
    <div class="feature-categories">
        <ul>
            <?php
                if($enabledCategoriesId = $this->getCategoriesId()):
                    foreach($enabledCategoriesId as $enabledCategoryId):
                        $categoryProducts = $this->getCategoryProducts($enabledCategoryId);
                            foreach($categoryProducts as $_product):
            ?>
                        <li class="feature-products">
                            <div class="feature-product-image">
                                <a href="<?= $_product->getProductUrl() ?>">
                                    <img src="<?= $this->getProductImage($_product->getId()) ?>"/>
                                </a>
                            </div>
                            <h3 class="product-name">
                                <a href="<?= $_product->getProductUrl() ?>">
                                    <span><?= $_product->getName() ?> </span>
                                </a>
                            </h3>
                            <div class="price-box">
                                <div class="regular-price">
                                    <span>Regular Price</span>
                                    <span>R$ <?= number_format($_product->getPrice(),2,",",".") ?></span>
                                </div>
                                <?php
                                $_product->setCustomerGroupId(4);
                                if($_product->getGroupPrice() != $_product->getPrice()):
                                ?>
                                    <div class="group-price">
                                        <span>Group Price</span>
                                        <span>R$ <?= number_format($_product->getGroupPrice(),2,",",".") ?></span>
                                    </div>
                                <?php endif; ?>
                            </div>
                            <div class="actions"></div>
                        </li>
            <?php
                            endforeach;
                    endforeach;
                endif;
            ?>
        </ul>
    </div>
</div>
<?php endif; ?>